# Generated by Django 2.2.6 on 2024-01-22 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0002_recipeplan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='prepation_time',
            new_name='preparation_time',
        ),
    ]
