# Generated by Django 2.2.6 on 2024-01-22 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0003_auto_20240122_2133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeplan',
            old_name='plan_id',
            new_name='plan',
        ),
        migrations.RenameField(
            model_name='recipeplan',
            old_name='recipe_id',
            new_name='recipe',
        ),
    ]
