# Generated by Django 2.2.6 on 2024-01-23 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0005_auto_20240122_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeplan',
            name='day_name',
            field=models.CharField(choices=[('Poniedziałek', 'Poniedziałek'), ('Wtorek', 'Wtorek'), ('Środa', 'Środa'), ('Czwartek', 'Czwartek'), ('Piątek', 'Piątek'), ('Sobota', 'Sobota'), ('Niedziela', 'Niedziela')], default='Poniedziałek', max_length=20),
        ),
    ]
