# Generated by Django 2.2.6 on 2024-01-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0007_auto_20240123_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeplan',
            name='day_name',
            field=models.CharField(choices=[('MON', 'Poniedziałek'), ('TUE', 'Wtorek'), ('WED', 'Środa'), ('THU', 'Czwartek'), ('FRI', 'Piątek'), ('SAT', 'Sobota'), ('SUN', 'Niedziela')], default='Poniedziałek', max_length=20),
        ),
    ]
